/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DocsAdminRouteImport } from './routes/docs-admin'
import { Route as HqRouteImport } from './routes/hq'
import { Route as IngestRouteImport } from './routes/ingest'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SystemRouteImport } from './routes/system'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as DocsSlugRouteImport } from './routes/docs_.$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as DocsAdminEditorSlugRouteImport } from './routes/docs-admin_.editor.$slug'
import { Route as ApiPublicAgentCallStartRouteImport } from './routes/api/public/agent/call-start'
import { Route as ApiPublicAgentCoachRouteImport } from './routes/api/public/agent/coach'
import { Route as ApiPublicAgentLoginRouteImport } from './routes/api/public/agent/login'
import { Route as ApiPublicAgentPresenceRouteImport } from './routes/api/public/agent/presence'
import { Route as ApiPublicAgentReportRouteImport } from './routes/api/public/agent/report'
import { Route as ApiPublicAgentVersionRouteImport } from './routes/api/public/agent/version'
import { Route as ApiPublicAgentWorkspaceRouteImport } from './routes/api/public/agent/workspace'
import { Route as ApiPublicConfigRulesRouteImport } from './routes/api/public/config/rules'
import { Route as ApiPublicDownloadApkRouteImport } from './routes/api/public/download/apk'
import { Route as ApiPublicIngestAnalyzeRouteImport } from './routes/api/public/ingest/analyze'
import { Route as ApiPublicIngestLeadRouteImport } from './routes/api/public/ingest/lead'
import { Route as ApiPublicIngestMessageRouteImport } from './routes/api/public/ingest/message'
import { Route as ApiPublicIngestOutcomeRouteImport } from './routes/api/public/ingest/outcome'
import { Route as ApiPublicIngestRecordingRouteImport } from './routes/api/public/ingest/recording'
import { Route as ApiPublicIngestReprocessRouteImport } from './routes/api/public/ingest/reprocess'
import { Route as ApiPublicPaddleWebhookRouteImport } from './routes/api/public/paddle/webhook'
import { Route as ApiPublicReportsSummaryRouteImport } from './routes/api/public/reports/summary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAdminRoute = DocsAdminRouteImport.update({
  id: '/docs-admin',
  path: '/docs-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HqRoute = HqRouteImport.update({
  id: '/hq',
  path: '/hq',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestRoute = IngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs_/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAdminEditorSlugRoute = DocsAdminEditorSlugRouteImport.update({
  id: '/docs-admin_/editor/$slug',
  path: '/docs-admin/editor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentCallStartRoute = ApiPublicAgentCallStartRouteImport.update({
  id: '/api/public/agent/call-start',
  path: '/api/public/agent/call-start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentCoachRoute = ApiPublicAgentCoachRouteImport.update({
  id: '/api/public/agent/coach',
  path: '/api/public/agent/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentLoginRoute = ApiPublicAgentLoginRouteImport.update({
  id: '/api/public/agent/login',
  path: '/api/public/agent/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentPresenceRoute = ApiPublicAgentPresenceRouteImport.update({
  id: '/api/public/agent/presence',
  path: '/api/public/agent/presence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentReportRoute = ApiPublicAgentReportRouteImport.update({
  id: '/api/public/agent/report',
  path: '/api/public/agent/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentVersionRoute = ApiPublicAgentVersionRouteImport.update({
  id: '/api/public/agent/version',
  path: '/api/public/agent/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentWorkspaceRoute = ApiPublicAgentWorkspaceRouteImport.update({
  id: '/api/public/agent/workspace',
  path: '/api/public/agent/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConfigRulesRoute = ApiPublicConfigRulesRouteImport.update({
  id: '/api/public/config/rules',
  path: '/api/public/config/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDownloadApkRoute = ApiPublicDownloadApkRouteImport.update({
  id: '/api/public/download/apk',
  path: '/api/public/download/apk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestAnalyzeRoute = ApiPublicIngestAnalyzeRouteImport.update({
  id: '/api/public/ingest/analyze',
  path: '/api/public/ingest/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestLeadRoute = ApiPublicIngestLeadRouteImport.update({
  id: '/api/public/ingest/lead',
  path: '/api/public/ingest/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestMessageRoute = ApiPublicIngestMessageRouteImport.update({
  id: '/api/public/ingest/message',
  path: '/api/public/ingest/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestOutcomeRoute = ApiPublicIngestOutcomeRouteImport.update({
  id: '/api/public/ingest/outcome',
  path: '/api/public/ingest/outcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRecordingRoute =
  ApiPublicIngestRecordingRouteImport.update({
    id: '/api/public/ingest/recording',
    path: '/api/public/ingest/recording',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIngestReprocessRoute =
  ApiPublicIngestReprocessRouteImport.update({
    id: '/api/public/ingest/reprocess',
    path: '/api/public/ingest/reprocess',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaddleWebhookRoute = ApiPublicPaddleWebhookRouteImport.update({
  id: '/api/public/paddle/webhook',
  path: '/api/public/paddle/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReportsSummaryRoute = ApiPublicReportsSummaryRouteImport.update({
  id: '/api/public/reports/summary',
  path: '/api/public/reports/summary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/desk': typeof DeskRoute
  '/dispatch': typeof DispatchRoute
  '/docs': typeof DocsRoute
  '/docs-admin': typeof DocsAdminRoute
  '/hq': typeof HqRoute
  '/ingest': typeof IngestRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/system': typeof SystemRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/docs-admin/editor/$slug': typeof DocsAdminEditorSlugRoute
  '/api/public/agent/call-start': typeof ApiPublicAgentCallStartRoute
  '/api/public/agent/coach': typeof ApiPublicAgentCoachRoute
  '/api/public/agent/login': typeof ApiPublicAgentLoginRoute
  '/api/public/agent/presence': typeof ApiPublicAgentPresenceRoute
  '/api/public/agent/report': typeof ApiPublicAgentReportRoute
  '/api/public/agent/version': typeof ApiPublicAgentVersionRoute
  '/api/public/agent/workspace': typeof ApiPublicAgentWorkspaceRoute
  '/api/public/config/rules': typeof ApiPublicConfigRulesRoute
  '/api/public/download/apk': typeof ApiPublicDownloadApkRoute
  '/api/public/ingest/analyze': typeof ApiPublicIngestAnalyzeRoute
  '/api/public/ingest/lead': typeof ApiPublicIngestLeadRoute
  '/api/public/ingest/message': typeof ApiPublicIngestMessageRoute
  '/api/public/ingest/outcome': typeof ApiPublicIngestOutcomeRoute
  '/api/public/ingest/recording': typeof ApiPublicIngestRecordingRoute
  '/api/public/ingest/reprocess': typeof ApiPublicIngestReprocessRoute
  '/api/public/paddle/webhook': typeof ApiPublicPaddleWebhookRoute
  '/api/public/reports/summary': typeof ApiPublicReportsSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/desk': typeof DeskRoute
  '/dispatch': typeof DispatchRoute
  '/docs': typeof DocsRoute
  '/docs-admin': typeof DocsAdminRoute
  '/hq': typeof HqRoute
  '/ingest': typeof IngestRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/system': typeof SystemRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/docs-admin/editor/$slug': typeof DocsAdminEditorSlugRoute
  '/api/public/agent/call-start': typeof ApiPublicAgentCallStartRoute
  '/api/public/agent/coach': typeof ApiPublicAgentCoachRoute
  '/api/public/agent/login': typeof ApiPublicAgentLoginRoute
  '/api/public/agent/presence': typeof ApiPublicAgentPresenceRoute
  '/api/public/agent/report': typeof ApiPublicAgentReportRoute
  '/api/public/agent/version': typeof ApiPublicAgentVersionRoute
  '/api/public/agent/workspace': typeof ApiPublicAgentWorkspaceRoute
  '/api/public/config/rules': typeof ApiPublicConfigRulesRoute
  '/api/public/download/apk': typeof ApiPublicDownloadApkRoute
  '/api/public/ingest/analyze': typeof ApiPublicIngestAnalyzeRoute
  '/api/public/ingest/lead': typeof ApiPublicIngestLeadRoute
  '/api/public/ingest/message': typeof ApiPublicIngestMessageRoute
  '/api/public/ingest/outcome': typeof ApiPublicIngestOutcomeRoute
  '/api/public/ingest/recording': typeof ApiPublicIngestRecordingRoute
  '/api/public/ingest/reprocess': typeof ApiPublicIngestReprocessRoute
  '/api/public/paddle/webhook': typeof ApiPublicPaddleWebhookRoute
  '/api/public/reports/summary': typeof ApiPublicReportsSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/desk': typeof DeskRoute
  '/dispatch': typeof DispatchRoute
  '/docs': typeof DocsRoute
  '/docs-admin': typeof DocsAdminRoute
  '/hq': typeof HqRoute
  '/ingest': typeof IngestRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/system': typeof SystemRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/docs_/$slug': typeof DocsSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/docs-admin_/editor/$slug': typeof DocsAdminEditorSlugRoute
  '/api/public/agent/call-start': typeof ApiPublicAgentCallStartRoute
  '/api/public/agent/coach': typeof ApiPublicAgentCoachRoute
  '/api/public/agent/login': typeof ApiPublicAgentLoginRoute
  '/api/public/agent/presence': typeof ApiPublicAgentPresenceRoute
  '/api/public/agent/report': typeof ApiPublicAgentReportRoute
  '/api/public/agent/version': typeof ApiPublicAgentVersionRoute
  '/api/public/agent/workspace': typeof ApiPublicAgentWorkspaceRoute
  '/api/public/config/rules': typeof ApiPublicConfigRulesRoute
  '/api/public/download/apk': typeof ApiPublicDownloadApkRoute
  '/api/public/ingest/analyze': typeof ApiPublicIngestAnalyzeRoute
  '/api/public/ingest/lead': typeof ApiPublicIngestLeadRoute
  '/api/public/ingest/message': typeof ApiPublicIngestMessageRoute
  '/api/public/ingest/outcome': typeof ApiPublicIngestOutcomeRoute
  '/api/public/ingest/recording': typeof ApiPublicIngestRecordingRoute
  '/api/public/ingest/reprocess': typeof ApiPublicIngestReprocessRoute
  '/api/public/paddle/webhook': typeof ApiPublicPaddleWebhookRoute
  '/api/public/reports/summary': typeof ApiPublicReportsSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/coach'
    | '/desk'
    | '/dispatch'
    | '/docs'
    | '/docs-admin'
    | '/hq'
    | '/ingest'
    | '/mcp'
    | '/privacy'
    | '/reports'
    | '/system'
    | '/terms'
    | '/.well-known/oauth-protected-resource'
    | '/docs/$slug'
    | '/.lovable/oauth/consent'
    | '/docs-admin/editor/$slug'
    | '/api/public/agent/call-start'
    | '/api/public/agent/coach'
    | '/api/public/agent/login'
    | '/api/public/agent/presence'
    | '/api/public/agent/report'
    | '/api/public/agent/version'
    | '/api/public/agent/workspace'
    | '/api/public/config/rules'
    | '/api/public/download/apk'
    | '/api/public/ingest/analyze'
    | '/api/public/ingest/lead'
    | '/api/public/ingest/message'
    | '/api/public/ingest/outcome'
    | '/api/public/ingest/recording'
    | '/api/public/ingest/reprocess'
    | '/api/public/paddle/webhook'
    | '/api/public/reports/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/coach'
    | '/desk'
    | '/dispatch'
    | '/docs'
    | '/docs-admin'
    | '/hq'
    | '/ingest'
    | '/mcp'
    | '/privacy'
    | '/reports'
    | '/system'
    | '/terms'
    | '/.well-known/oauth-protected-resource'
    | '/docs/$slug'
    | '/.lovable/oauth/consent'
    | '/docs-admin/editor/$slug'
    | '/api/public/agent/call-start'
    | '/api/public/agent/coach'
    | '/api/public/agent/login'
    | '/api/public/agent/presence'
    | '/api/public/agent/report'
    | '/api/public/agent/version'
    | '/api/public/agent/workspace'
    | '/api/public/config/rules'
    | '/api/public/download/apk'
    | '/api/public/ingest/analyze'
    | '/api/public/ingest/lead'
    | '/api/public/ingest/message'
    | '/api/public/ingest/outcome'
    | '/api/public/ingest/recording'
    | '/api/public/ingest/reprocess'
    | '/api/public/paddle/webhook'
    | '/api/public/reports/summary'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/coach'
    | '/desk'
    | '/dispatch'
    | '/docs'
    | '/docs-admin'
    | '/hq'
    | '/ingest'
    | '/mcp'
    | '/privacy'
    | '/reports'
    | '/system'
    | '/terms'
    | '/.well-known/oauth-protected-resource'
    | '/docs_/$slug'
    | '/.lovable/oauth/consent'
    | '/docs-admin_/editor/$slug'
    | '/api/public/agent/call-start'
    | '/api/public/agent/coach'
    | '/api/public/agent/login'
    | '/api/public/agent/presence'
    | '/api/public/agent/report'
    | '/api/public/agent/version'
    | '/api/public/agent/workspace'
    | '/api/public/config/rules'
    | '/api/public/download/apk'
    | '/api/public/ingest/analyze'
    | '/api/public/ingest/lead'
    | '/api/public/ingest/message'
    | '/api/public/ingest/outcome'
    | '/api/public/ingest/recording'
    | '/api/public/ingest/reprocess'
    | '/api/public/paddle/webhook'
    | '/api/public/reports/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CoachRoute: typeof CoachRoute
  DeskRoute: typeof DeskRoute
  DispatchRoute: typeof DispatchRoute
  DocsRoute: typeof DocsRoute
  DocsAdminRoute: typeof DocsAdminRoute
  HqRoute: typeof HqRoute
  IngestRoute: typeof IngestRoute
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportsRoute: typeof ReportsRoute
  SystemRoute: typeof SystemRoute
  TermsRoute: typeof TermsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DocsSlugRoute: typeof DocsSlugRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  DocsAdminEditorSlugRoute: typeof DocsAdminEditorSlugRoute
  ApiPublicAgentCallStartRoute: typeof ApiPublicAgentCallStartRoute
  ApiPublicAgentCoachRoute: typeof ApiPublicAgentCoachRoute
  ApiPublicAgentLoginRoute: typeof ApiPublicAgentLoginRoute
  ApiPublicAgentPresenceRoute: typeof ApiPublicAgentPresenceRoute
  ApiPublicAgentReportRoute: typeof ApiPublicAgentReportRoute
  ApiPublicAgentVersionRoute: typeof ApiPublicAgentVersionRoute
  ApiPublicAgentWorkspaceRoute: typeof ApiPublicAgentWorkspaceRoute
  ApiPublicConfigRulesRoute: typeof ApiPublicConfigRulesRoute
  ApiPublicDownloadApkRoute: typeof ApiPublicDownloadApkRoute
  ApiPublicIngestAnalyzeRoute: typeof ApiPublicIngestAnalyzeRoute
  ApiPublicIngestLeadRoute: typeof ApiPublicIngestLeadRoute
  ApiPublicIngestMessageRoute: typeof ApiPublicIngestMessageRoute
  ApiPublicIngestOutcomeRoute: typeof ApiPublicIngestOutcomeRoute
  ApiPublicIngestRecordingRoute: typeof ApiPublicIngestRecordingRoute
  ApiPublicIngestReprocessRoute: typeof ApiPublicIngestReprocessRoute
  ApiPublicPaddleWebhookRoute: typeof ApiPublicPaddleWebhookRoute
  ApiPublicReportsSummaryRoute: typeof ApiPublicReportsSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs-admin': {
      id: '/docs-admin'
      path: '/docs-admin'
      fullPath: '/docs-admin'
      preLoaderRoute: typeof DocsAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq': {
      id: '/hq'
      path: '/hq'
      fullPath: '/hq'
      preLoaderRoute: typeof HqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest': {
      id: '/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs_/$slug': {
      id: '/docs_/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs-admin_/editor/$slug': {
      id: '/docs-admin_/editor/$slug'
      path: '/docs-admin/editor/$slug'
      fullPath: '/docs-admin/editor/$slug'
      preLoaderRoute: typeof DocsAdminEditorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/call-start': {
      id: '/api/public/agent/call-start'
      path: '/api/public/agent/call-start'
      fullPath: '/api/public/agent/call-start'
      preLoaderRoute: typeof ApiPublicAgentCallStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/coach': {
      id: '/api/public/agent/coach'
      path: '/api/public/agent/coach'
      fullPath: '/api/public/agent/coach'
      preLoaderRoute: typeof ApiPublicAgentCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/login': {
      id: '/api/public/agent/login'
      path: '/api/public/agent/login'
      fullPath: '/api/public/agent/login'
      preLoaderRoute: typeof ApiPublicAgentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/presence': {
      id: '/api/public/agent/presence'
      path: '/api/public/agent/presence'
      fullPath: '/api/public/agent/presence'
      preLoaderRoute: typeof ApiPublicAgentPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/report': {
      id: '/api/public/agent/report'
      path: '/api/public/agent/report'
      fullPath: '/api/public/agent/report'
      preLoaderRoute: typeof ApiPublicAgentReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/version': {
      id: '/api/public/agent/version'
      path: '/api/public/agent/version'
      fullPath: '/api/public/agent/version'
      preLoaderRoute: typeof ApiPublicAgentVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/workspace': {
      id: '/api/public/agent/workspace'
      path: '/api/public/agent/workspace'
      fullPath: '/api/public/agent/workspace'
      preLoaderRoute: typeof ApiPublicAgentWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/config/rules': {
      id: '/api/public/config/rules'
      path: '/api/public/config/rules'
      fullPath: '/api/public/config/rules'
      preLoaderRoute: typeof ApiPublicConfigRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/download/apk': {
      id: '/api/public/download/apk'
      path: '/api/public/download/apk'
      fullPath: '/api/public/download/apk'
      preLoaderRoute: typeof ApiPublicDownloadApkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/analyze': {
      id: '/api/public/ingest/analyze'
      path: '/api/public/ingest/analyze'
      fullPath: '/api/public/ingest/analyze'
      preLoaderRoute: typeof ApiPublicIngestAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/lead': {
      id: '/api/public/ingest/lead'
      path: '/api/public/ingest/lead'
      fullPath: '/api/public/ingest/lead'
      preLoaderRoute: typeof ApiPublicIngestLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/message': {
      id: '/api/public/ingest/message'
      path: '/api/public/ingest/message'
      fullPath: '/api/public/ingest/message'
      preLoaderRoute: typeof ApiPublicIngestMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/outcome': {
      id: '/api/public/ingest/outcome'
      path: '/api/public/ingest/outcome'
      fullPath: '/api/public/ingest/outcome'
      preLoaderRoute: typeof ApiPublicIngestOutcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/recording': {
      id: '/api/public/ingest/recording'
      path: '/api/public/ingest/recording'
      fullPath: '/api/public/ingest/recording'
      preLoaderRoute: typeof ApiPublicIngestRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/reprocess': {
      id: '/api/public/ingest/reprocess'
      path: '/api/public/ingest/reprocess'
      fullPath: '/api/public/ingest/reprocess'
      preLoaderRoute: typeof ApiPublicIngestReprocessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paddle/webhook': {
      id: '/api/public/paddle/webhook'
      path: '/api/public/paddle/webhook'
      fullPath: '/api/public/paddle/webhook'
      preLoaderRoute: typeof ApiPublicPaddleWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reports/summary': {
      id: '/api/public/reports/summary'
      path: '/api/public/reports/summary'
      fullPath: '/api/public/reports/summary'
      preLoaderRoute: typeof ApiPublicReportsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CoachRoute: CoachRoute,
  DeskRoute: DeskRoute,
  DispatchRoute: DispatchRoute,
  DocsRoute: DocsRoute,
  DocsAdminRoute: DocsAdminRoute,
  HqRoute: HqRoute,
  IngestRoute: IngestRoute,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  ReportsRoute: ReportsRoute,
  SystemRoute: SystemRoute,
  TermsRoute: TermsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DocsSlugRoute: DocsSlugRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  DocsAdminEditorSlugRoute: DocsAdminEditorSlugRoute,
  ApiPublicAgentCallStartRoute: ApiPublicAgentCallStartRoute,
  ApiPublicAgentCoachRoute: ApiPublicAgentCoachRoute,
  ApiPublicAgentLoginRoute: ApiPublicAgentLoginRoute,
  ApiPublicAgentPresenceRoute: ApiPublicAgentPresenceRoute,
  ApiPublicAgentReportRoute: ApiPublicAgentReportRoute,
  ApiPublicAgentVersionRoute: ApiPublicAgentVersionRoute,
  ApiPublicAgentWorkspaceRoute: ApiPublicAgentWorkspaceRoute,
  ApiPublicConfigRulesRoute: ApiPublicConfigRulesRoute,
  ApiPublicDownloadApkRoute: ApiPublicDownloadApkRoute,
  ApiPublicIngestAnalyzeRoute: ApiPublicIngestAnalyzeRoute,
  ApiPublicIngestLeadRoute: ApiPublicIngestLeadRoute,
  ApiPublicIngestMessageRoute: ApiPublicIngestMessageRoute,
  ApiPublicIngestOutcomeRoute: ApiPublicIngestOutcomeRoute,
  ApiPublicIngestRecordingRoute: ApiPublicIngestRecordingRoute,
  ApiPublicIngestReprocessRoute: ApiPublicIngestReprocessRoute,
  ApiPublicPaddleWebhookRoute: ApiPublicPaddleWebhookRoute,
  ApiPublicReportsSummaryRoute: ApiPublicReportsSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
