/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HqRouteImport } from './routes/hq'
import { Route as ApiPublicIngestMessageRouteImport } from './routes/api/public/ingest/message'
import { Route as ApiPublicIngestRecordingRouteImport } from './routes/api/public/ingest/recording'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HqRoute = HqRouteImport.update({
  id: '/hq',
  path: '/hq',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestMessageRoute = ApiPublicIngestMessageRouteImport.update({
  id: '/api/public/ingest/message',
  path: '/api/public/ingest/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRecordingRoute =
  ApiPublicIngestRecordingRouteImport.update({
    id: '/api/public/ingest/recording',
    path: '/api/public/ingest/recording',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hq': typeof HqRoute
  '/api/public/ingest/message': typeof ApiPublicIngestMessageRoute
  '/api/public/ingest/recording': typeof ApiPublicIngestRecordingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hq': typeof HqRoute
  '/api/public/ingest/message': typeof ApiPublicIngestMessageRoute
  '/api/public/ingest/recording': typeof ApiPublicIngestRecordingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hq': typeof HqRoute
  '/api/public/ingest/message': typeof ApiPublicIngestMessageRoute
  '/api/public/ingest/recording': typeof ApiPublicIngestRecordingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/hq' | '/api/public/ingest/message' | '/api/public/ingest/recording'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/hq' | '/api/public/ingest/message' | '/api/public/ingest/recording'
  id:
    | '__root__'
    | '/'
    | '/hq'
    | '/api/public/ingest/message'
    | '/api/public/ingest/recording'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HqRoute: typeof HqRoute
  ApiPublicIngestMessageRoute: typeof ApiPublicIngestMessageRoute
  ApiPublicIngestRecordingRoute: typeof ApiPublicIngestRecordingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq': {
      id: '/hq'
      path: '/hq'
      fullPath: '/hq'
      preLoaderRoute: typeof HqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/message': {
      id: '/api/public/ingest/message'
      path: '/api/public/ingest/message'
      fullPath: '/api/public/ingest/message'
      preLoaderRoute: typeof ApiPublicIngestMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/recording': {
      id: '/api/public/ingest/recording'
      path: '/api/public/ingest/recording'
      fullPath: '/api/public/ingest/recording'
      preLoaderRoute: typeof ApiPublicIngestRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HqRoute: HqRoute,
  ApiPublicIngestMessageRoute: ApiPublicIngestMessageRoute,
  ApiPublicIngestRecordingRoute: ApiPublicIngestRecordingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
